version: '3.3'
#volumes:
#  local_postgres_data: { }
#  local_postgres_data_backups: { }
services:
  tech_store_serv_dev:
    build:
      context: .
      dockerfile: ./.docker-compose/dev/django/Dockerfile
    image: tech_store_serv_dev
    container_name: tech_store_serv_dev
    #    depends_on:
    #      - postgres
    volumes:
      - .:/serv:z
    #    env_file:
    #      - ./.envs/.local/.django
    #      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
