#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
python manage.py makemigrations
python manage.py migrate
python manage.py collectstatic --noinput

/usr/local/bin/gunicorn master_serv.asgi --bind 0.0.0.0:8000 --chdir=/serv -k uvicorn.workers.UvicornWorker
