# Generated by Django 4.0 on 2022-07-04 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Modified')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DELETED', 'DELETED')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status')),
                ('brand_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'warehouse_brand',
                'ordering': ['brand_id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Modified')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DELETED', 'DELETED')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status')),
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('code', models.CharField(max_length=5, verbose_name='code')),
                ('description', models.CharField(max_length=30, verbose_name='Description')),
                ('order', models.IntegerField(verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'warehouse_category',
                'ordering': ['category_id'],
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Modified')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DELETED', 'DELETED')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status')),
                ('presentation_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('description', models.CharField(default='-', max_length=20, verbose_name='Presentation')),
                ('is_min', models.BooleanField(default=True, verbose_name='IsMin')),
            ],
            options={
                'verbose_name': 'Presentation',
                'verbose_name_plural': 'Presentations',
                'db_table': 'warehouse_presentation',
                'ordering': ['presentation_id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Modified')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DELETED', 'DELETED')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status')),
                ('product_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('sku', models.CharField(max_length=10, verbose_name='SKU')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('small_description', models.CharField(max_length=50, verbose_name='Small Description')),
                ('is_new', models.BooleanField(default=True, verbose_name='Is New')),
                ('actual_price', models.FloatField(blank=True, default=0, null=True, verbose_name='Price')),
                ('brand', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.brand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'warehouse_product',
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Modified')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DELETED', 'DELETED')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status')),
                ('specification_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(default='-', max_length=50, verbose_name='Name')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Specification',
                'verbose_name_plural': 'Specifications',
                'db_table': 'warehouse_specification',
                'ordering': ['specification_id'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Modified')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DELETED', 'DELETED')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status')),
                ('unit_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('abbreviation', models.CharField(max_length=5, verbose_name='Abbreviation')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'warehouse_unit',
                'ordering': ['unit_id'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Modified')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DELETED', 'DELETED')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status')),
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('code', models.CharField(max_length=5, verbose_name='code')),
                ('description', models.CharField(max_length=30, verbose_name='Description')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'db_table': 'warehouse_subcategory',
                'ordering': ['subcategory_id'],
            },
        ),
        migrations.CreateModel(
            name='SpecificationDetail',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Modified')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DELETED', 'DELETED')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status')),
                ('specification_detail_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('key', models.CharField(blank=True, max_length=20, null=True, verbose_name='Key')),
                ('value', models.CharField(default='-', max_length=50, verbose_name='Value')),
                ('specification', models.ForeignKey(db_column='specification_id', on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.specification', verbose_name='Specification')),
            ],
            options={
                'verbose_name': 'Specification Detail',
                'verbose_name_plural': 'Specification Detail',
                'db_table': 'warehouse_specification_detail',
                'ordering': ['specification_detail_id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Modified')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DELETED', 'DELETED')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status')),
                ('product_subcategory_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.product', verbose_name='Product')),
                ('subcategory', models.ForeignKey(db_column='subcategory_id', on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.subcategory', verbose_name='Product Subcategory')),
            ],
            options={
                'verbose_name': 'Product Subcategory',
                'verbose_name_plural': 'Product Subcategories',
                'db_table': 'warehouse_product_subcategory',
                'ordering': ['product_subcategory_id'],
            },
        ),
        migrations.CreateModel(
            name='ProductPresentation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Modified')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('DELETED', 'DELETED')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status')),
                ('product_presentation_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('presentation', models.ForeignKey(db_column='presentation_id', on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.presentation', verbose_name='Presentation')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Presentation',
                'verbose_name_plural': 'Product Presentations',
                'db_table': 'warehouse_product_presentation',
                'ordering': ['product_presentation_id'],
            },
        ),
        migrations.AddField(
            model_name='presentation',
            name='unit',
            field=models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.unit', verbose_name='Unit'),
        ),
    ]
