# Generated by Django 4.0 on 2022-09-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('DELETED', 'DELETED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('DELETED', 'DELETED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('DELETED', 'DELETED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('DELETED', 'DELETED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='productpresentation',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('DELETED', 'DELETED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('DELETED', 'DELETED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('DELETED', 'DELETED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='specificationdetail',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('DELETED', 'DELETED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('DELETED', 'DELETED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('DELETED', 'DELETED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status'),
        ),
    ]
