# Generated by Django 4.0 on 2023-10-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_brand_status_alter_category_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Manufacturer Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Product Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_level',
            field=models.CharField(blank=True, choices=[('marca', 'Marca'), ('mayorista', 'Mayorista')], max_length=10, null=True, verbose_name='Warranty Level'),
        ),
    ]
