# Generated by Django 4.0 on 2023-10-06 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_productinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOutput',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Modified')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('DELETED', 'DELETED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status')),
                ('product_output_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='Movement Date')),
                ('reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reason')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Output',
                'verbose_name_plural': 'Product Outputs',
                'db_table': 'warehouse_product_output',
                'ordering': ['product_output_id'],
            },
        ),
    ]
